### ISSUE TITLE
Unable to update the field 

### ISSUE THREAD

**Issue by ysidheshwar** [ermouth/covercouch#5]
- This approach has been fixed for my project, I have only this source to clear my quires so need help 
 eagerly 
- When i'm trying to update document with passing creator,owner ,acl fields from pouch with same user
  which is requesting to couchdb then i can see updated value in couchdb log but problem is updated
  values are not reflecting.
- Even I have tried with refreshing couchdb but it not worked.
- The log I have got as follow :+1: 

> old-doc object is 
{"_id":"d3b00713-b378-47ce-aa27-16e83979b1f8","_rev":"1-50a24cd2359344a29bfbcf502d8be018",**"title":"testing 1"**,"creator":["sidhu"],"owner":["sidhu"],"acl":["sidhu"],"_revisions":{"start":1,"ids":["50a24cd2359344a29bfbcf502d8be018"]}}  .
- New doc object is
{"_id":"d3b00713-b378-47ce-aa27-16e83979b1f8","_rev":"2-44d3b0e327444e3bb59d6c3eb2fcbd11",**"title":"tested 1 doc**","creator":["sidhu"],"owners":["sidhu"],"acl":["sidhu"],"_revisions":{"start":2,"ids":["44d3b0e327444e3bb59d6c3eb2fcbd11","50a24cd2359344a29bfbcf502d8be018"]}}

please help.

**Comment by ermouth** [comment]
Let me explain more verbosely:

1. This lib was written 3 years ago and I never touched it since that time.
2. This lib uses other libs, which may be updated with breaking dependencies.
3. This lib was never tested with Couch 2.x, new node.js and new PouchDB.
4. I _explicitly_ marked lib as beta.

So I can‘t go in deep of your problem. Also please note, that both times you have not bothered to provide _any_ reasonable info about your environment.
